sudo: false
language: node_js
node_js:  
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - commitlint-travis
  - npm run test
after_success:
 - npm run semantic-release