sudo: false
language: node_js
node_js:  
  - "node"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - commitlint-travis
  - npm run test
after_success:
 - npm run build:lib
 - npm run build:go-to-lib
 - npm run semantic-release